### ISSUE TITLE
Check if device is offline or online

### ISSUE THREAD

**Issue by AgentHarm** [Makhuta/homeassistant-honeygain_scrapper#1]
Hey love the integration for Homeassistant, super easy to use, though I thought I'd suggest an additional feature if possible:

An active device's icon has an opacity of 1:
![image](https://github.com/Makhuta/homeassistant-honeygain_scrapper/assets/105981445/79d5ea8b-21e8-4777-aa62-c19612f1d94e)

Whereas a device that has gone offline has an opacity of 0.2
![image](https://github.com/Makhuta/homeassistant-honeygain_scrapper/assets/105981445/c1bd31db-6c83-4346-b3e5-7b2713de926f)

Is there any way of using these as a way of adding this as an entity? or maybe just an attribute of the device entity already pushed to home assistant? Would make it easy to get an alert that one has stopped or trigger a reboot of a machine.

**Comment by Makhuta** [comment]
I am not sure if I understand you correctly can you please provide some more info (for the opacity)?
And for the devices what do you mean by "adding as an entity" each device that you've got connected to your HG account is separate entity (sensor) with its own attributes and the attributes in the sensors contains most of if not all of what HG API provides, I could look into it little bit more if there is some way to show if the device is online or not but can't promise anything.

Edit: It might be possible but I need to modify (rewrite) the api that I am using

**Comment by Makhuta** [comment]
I've just pushed new release [V1.0.6](https://github.com/Makhuta/homeassistant-honeygain_scrapper/releases/tag/v1.0.6).

It changes the states displayed by devices from their IDs to their availability, for example if the device is active it show True otherwise it shows False.
Also there is a little bit different (additional) info for the devices that is active or has been active in recent 14 days (just like on the page) it will not only show the data as before but also the IP, Status ("active"/"inactive") and last active time.

**Comment by AgentHarm** [comment]
Hey,

Works great! they're reporting as True/False now so that I can trigger reboots based on that!

**Comment by Makhuta** [comment]
Glad to hear that, is it all you wanted to recomend? Because I don't think it is in my power to change the opacity like you described, if I understood correctly.

**Comment by AgentHarm** [comment]
Yeah I just pointed that out as a possible way to track up or down devices, as I wasn't sure if you were pulling from html on the site or something, but what you've implemented is perfect, thanks again!
